src/Models/DataContext.cs
using CedTruck.Models;
using Microsoft.EntityFrameworkCore;

namespace CedTruck
{
    public class DataContext : DbContext
    {
        public DataContext(DbContextOptions options) : base(options)
        {

        }

        public DbSet<Truck> Trucks { get; set; }
        
        public DbSet<TruckModel> TruckModels { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            modelBuilder.Entity<TruckModel>().HasData(
                new TruckModel { Id = 1, Model = "FH" },
                new TruckModel { Id = 2, Model = "FM" }
            );

        }
    }
}

src/Models/ErrorViewModel.cs
using System;

namespace CedTruck.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Models/Truck.cs
using System.ComponentModel.DataAnnotations;

namespace CedTruck.Models
{
    public class Truck
    {
        [Key]
        public long Id { get; set; }

        [Display(Name = "Truck Model Id")]
        public long ModelId { get; set; }
        
        [Display(Name = "Truck Model")]
        public TruckModel Model { get; set; }
        
        [Display(Name ="Fabrication Year")]
        public int YearFabrication { get; set; }
        
        [Display(Name = "Model Year")]
        public int YearModel { get; set; }



    }
}

src/Models/TruckModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CedTruck.Models
{
    public class TruckModel
    {
        [Key]
        public long Id { get; set; }

        [Display(Name = "Truck Model")]
        public String Model { get; set; }
    }
}

src/Controllers/HomeController.cs
using CedTruck.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace CedTruck.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Controllers/TrucksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CedTruck;
using CedTruck.Models;
using CedTruck.Services;
using CedTruck.Services.Interfaces;

namespace CedTruck.Controllers
{
    public class TrucksController : Controller
    {
        private readonly DataContext _context;
        private readonly ITrucksService _trucksService;

        public TrucksController(DataContext context, ITrucksService trucksService)
        {
            _context = context;
            _trucksService = trucksService;
        }

        // GET: Trucks
        public IActionResult Index()
        {
            var trucksList = _trucksService.GetAll(); //_context.Trucks.Include(t => t.Model);
            return View(trucksList);
        }

        // GET: Trucks/Details/5
        public IActionResult Details(long? id)
        {
            var truck = _trucksService.GetById(id);

            if (truck == null)
            {
                return NotFound();
            }

            return View(truck);
        }

        // GET: Trucks/Create
        public IActionResult Create()
        {
            ViewData["ModelId"] = new SelectList(_trucksService.GetAllTruckModels(), "Id", "Model");
            return View();
        }

        // POST: Trucks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ModelId,YearFabrication,YearModel")] Truck truck)
        {
            if (ModelState.IsValid)
            {
                _context.Add(truck);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ModelId"] = new SelectList(_trucksService.GetAllTruckModels(), "Id", "Model", truck.ModelId);
            return View(truck);
        }

        // GET: Trucks/Edit/5
        public IActionResult Edit(long? id)
        {
            var truck = _trucksService.GetById(id);

            if (truck == null)
            {
                return NotFound();
            }

            ViewData["ModelId"] = new SelectList(_context.TruckModels, "Id", "Model", truck.ModelId);
            return View(truck);
        }

        // POST: Trucks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,ModelId,YearFabrication,YearModel")] Truck truck)
        {
            if (id != truck.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(truck);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (null == _trucksService.GetById(truck.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ModelId"] = new SelectList(_trucksService.GetAllTruckModels(), "Id", "Model", truck.ModelId);
            return View(truck);
        }

        // GET: Trucks/Delete/5
        public IActionResult Delete(long? id)
        {
            var truck = _trucksService.GetById(id);

            if (truck == null)
            {
                return NotFound();
            }

            return View(truck);
        }

        // POST: Trucks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(long id)
        {
            _trucksService.DeleteById(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

src/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Prova Dev</h1>
    <p>An ingenious system for registering trucks </p>
</div>

src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CedTruck</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CedTruck</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trucks" asp-action="Index">Trucks</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CedTruck - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Views/Trucks/Create.cshtml
@model CedTruck.Models.Truck

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Truck</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ModelId" class="control-label"></label>
                <select asp-for="ModelId" class ="form-control" asp-items="ViewBag.ModelId"></select>
            </div>
            <div class="form-group">
                <label asp-for="YearFabrication" class="control-label"></label>
                <input asp-for="YearFabrication" class="form-control" />
                <span asp-validation-for="YearFabrication" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearModel" class="control-label"></label>
                <input asp-for="YearModel" class="form-control" />
                <span asp-validation-for="YearModel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Views/Trucks/Delete.cshtml
@model CedTruck.Models.Truck

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Truck</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YearFabrication)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YearFabrication)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YearModel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YearModel)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/Views/Trucks/Details.cshtml
@model CedTruck.Models.Truck

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Truck</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YearFabrication)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YearFabrication)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YearModel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YearModel)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/Views/Trucks/Edit.cshtml
@model CedTruck.Models.Truck

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Truck</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ModelId" class="control-label"></label>
                <select asp-for="ModelId" class="form-control" asp-items="ViewBag.ModelId"></select>
                <span asp-validation-for="ModelId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearFabrication" class="control-label"></label>
                <input asp-for="YearFabrication" class="form-control" />
                <span asp-validation-for="YearFabrication" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearModel" class="control-label"></label>
                <input asp-for="YearModel" class="form-control" />
                <span asp-validation-for="YearModel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Views/Trucks/Index.cshtml
@model IEnumerable<CedTruck.Models.Truck>

@{
    ViewData["Title"] = "Trucks";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New Truck</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.YearFabrication)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.YearModel)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Model.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YearFabrication)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YearModel)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>